export const ArabicText = {
    appName: 'إدارة مخزون البخور',
    common: {
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        add: 'إضافة',
        loading: 'جاري التحميل...',
        success: 'تم بنجاح',
        error: 'حدث خطأ',
        confirm: 'تأكيد',
        back: 'عودة',
        search: 'بحث...',
    },
    dashboard: {
        title: 'لوحة التحكم',
        newOrders: 'طلبات جديدة',
        packOrder: 'تعبئة طلب',
        addProduct: 'إضافة منتج',
        exportExcel: 'تصدير Excel',
        recentActivity: 'النشاط الأخير',
        lowStock: 'تنبيهات المخزون',
    },
    products: {
        title: 'المنتجات',
        sku: 'رمز المنتج (SKU)',
        name: 'اسم المنتج',
        weight: 'الوزن',
        stock: 'المخزون',
        kit: 'مكونات الطقم',
        samples: 'العينات',
    },
    orders: {
        title: 'الطلبات',
        pending: 'قيد الانتظار',
        packing: 'جاري التعبئة',
        completed: 'مكتمل',
        import: 'استيراد طلبات',
    },
    packing: {
        start: 'بدء التعبئة',
        finish: 'إنهاء التعبئة',
        complete: 'إتمام التعبئة',
        checklist: 'قائمة التعبئة',
        confirmFinish: 'هل أنت متأكد من إنهاء التعبئة؟',
    },
    giftCards: {
        title: 'بطاقات الهدايا',
        name: 'اسم البطاقة',
        sku: 'رمز البطاقة',
        soldSeparately: 'تباع منفصلة',
        bundled: 'مرفقة مع الطلبات',
    },
    kits: {
        title: 'مكونات الطقم',
        manageKit: 'إدارة المكونات',
        addComponent: 'إضافة مكون',
        removeComponent: 'إزالة مكون',
        quantity: 'الكمية',
        quickSelectAll: 'واحد من كل شيء',
        noComponents: 'لا توجد مكونات في هذا الطقم',
        selectComponents: 'اختر المكونات',
    },
    inventory: {
        import: 'استيراد المخزون',
        export: 'تصدير المخزون',
        components: 'المكونات',
        updateStock: 'تحديث المخزون',
    },
    templates: {
        title: 'قوالب الطلبات',
        createTemplate: 'إنشاء قالب',
        editTemplate: 'تعديل القالب',
        templateName: 'اسم القالب',
        applyTemplate: 'تطبيق القالب',
        noTemplates: 'لا توجد قوالب محفوظة',
        saveAsTemplate: 'حفظ كقالب',
    },
    tableView: {
        inventoryTable: 'جدول المخزون',
        ordersTable: 'جدول الطلبات',
    },
};

export default ArabicText;
